language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - 'travis_retry sudo apt-get update'
  - 'travis_retry sudo apt-get install python-dev libxml2-dev libxmlsec1-dev'
install:
  - pip install -r requirements.txt
before_script:
  - mv  config_template.py config.py
script:
  - sh run_travis.sh