name: powerdns-admin-test

services:
  python-tests:
    image: powerdns-admin-python-tests
    build:
      context: .
      dockerfile: docker-common/Dockerfile.app
      args:
        DOCKER_SCENARIO: docker-test
        INSTALL_TEST_DEPENDENCIES: "1"
    networks:
      - test
    env_file:
      - ./docker-test/env
    environment:
      FLASK_CONF: /app/configs/docker_config.py
      PDNS_API_KEY: ${PDNS_API_KEY:-changeme}
    tmpfs:
      - /data
    depends_on:
      - pdns-server

  pdns-server:
    image: powerdns-admin-python-tests-pdns
    build:
      context: .
      dockerfile: docker-common/Dockerfile.pdns
    networks:
      - test
    env_file:
      - ./docker-test/env
    environment:
      PDNS_API_KEY: ${PDNS_API_KEY:-changeme}
      PDNS_RESET_DATABASE: "1"

networks:
  test:
