version: "2.1"


services:
  powerdns-admin-ui-test:
    build:
      context: .
      dockerfile: docker/PowerDNS-Admin/Dockerfile
      args:
        - ENVIRONMENT=development
    image: powerdns-admin-ui-test
    container_name: powerdns-admin-ui-test
    mem_limit: 128M
    memswap_limit: 128M
    ports:
      - "9191:9191"
    volumes:
      - .:/powerdns-admin/
      - "./configs/${ENVIRONMENT}.py:/powerdns-admin/config.py"
      # Assets dir volume
      - powerdns-admin-ui-tests-assets:/powerdns-admin/app/static
      - powerdns-admin-ui-tests-assets2:/powerdns-admin/node_modules
      - powerdns-admin-ui-tests-assets3:/powerdns-admin/logs
      - ./app/static/custom:/powerdns-admin/app/static/custom
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    env_file:
      - ./env-ui-test
    depends_on:
      powerdns-admin-mysql-ui-test:
        condition: service_healthy
      pdns-server-ui-test:
        condition: service_started

  powerdns-admin-mysql-ui-test:
    image: mysql/mysql-server:5.7
    hostname: ${PDA_DB_HOST}
    container_name: powerdns-admin-mysql-ui-test
    mem_limit: 256M
    memswap_limit: 256M
    expose:
      - 3306
    networks:
      - default
    volumes:
      - powerdns-admin-mysql-ui-tests-data:/var/lib/mysql
    env_file:
      - ./env-ui-test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  pdns-server-ui-test:
    build:
      context: .
      dockerfile: docker/PowerDNS-Admin/Dockerfile.pdns.test
    image: pdns-server-ui-test
    container_name: pdns-server-ui-test
    mem_limit: 128M
    memswap_limit: 128M
    ports:
      - "5053:53"
      - "5053:53/udp"
    networks:
      - default
    env_file:
      - ./env-ui-test

  powerdns-admin-ui-test-tests:
    build:
      context: .
      dockerfile: docker/PowerDNS-Admin/Dockerfile.ui.test
      args:
        - ENVIRONMENT=development
    image: powerdns-admin-ui-test-tests
    env_file:
      - ./env-ui-test
    container_name: powerdns-admin-ui-test-tests
    volumes:
      - .:/powerdns-admin/
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    depends_on:
      - powerdns-admin-ui-test

networks:
  default:

volumes:
  powerdns-admin-mysql-ui-tests-data:
  powerdns-admin-ui-tests-assets:
  powerdns-admin-ui-tests-assets2:
  powerdns-admin-ui-tests-assets3:
