version: "3.3"

services:

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=qHZDZ26fPqqCfKZtWkQ9
      - MYSQL_DATABASE=pda
      - MYSQL_USER=pda
      - MYSQL_PASSWORD=qHZDZ26fPqqCfKZtWkQ9

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    depends_on: ['mysql']
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8082:80

  powerdns-admin:
    image: ngoduykhanh/powerdns-admin:latest
    depends_on: [ 'mysql' ]
    restart: unless-stopped
    environment:
      - PDA_BIND_ADDRESS=0.0.0.0
      - PDA_BIND_PORT=80
      - PDA_DEBUG=true
      - PDA_LOAD_ENV_FILES=true
      - PDA_AUTOINIT_ENABLED=true
      - PDA_AUTOINIT_FORCE=false
      - PDA_CHECK_MYSQL_ENABLED=true
      - PDA_CHECK_MYSQL_FAIL_DELAY=2
      - PDA_CHECK_MYSQL_SUCCESS_DELAY=0
      - PDA_CHECK_MYSQL_ATTEMPTS=30
      - PDA_CHECK_API_ENABLED=true
      - PDA_CHECK_API_FAIL_DELAY=2
      - PDA_CHECK_API_SUCCESS_DELAY=0
      - PDA_CHECK_API_ATTEMPTS=15
      - PDA_CHECK_PYTEST_ENABLED=false
      - PDA_GUNICORN_ENABLED=false
      - PDA_GUNICORN_TIMEOUT=2
      - PDA_GUNICORN_WORKERS=2
      - PDA_GUNICORN_LOGLEVEL=debug
      - PDA_PDNS_API_KEY=scjfNRN4Ch2DBuhk24vr
      - PDA_PDNS_VERSION=4.5.2
      - PDA_PDNS_PROTO=http
      - PDA_PDNS_HOST=pdns
      - PDA_PDNS_PORT=8081
      - PDA_ADMIN_USER_USERNAME=nocadmin
      - PDA_ADMIN_USER_PASSWORD=clink henchmen mete coracle uphold
      - PDAC_SALT=ntR8BmMQb7MKTJ5YrgQwZr3pxU3uLG
      - PDAC_SECRET_KEY=eJ92QLuennVStHTj5FVwxz7m4r3Ng3
      - PDAC_SIGNUP_ENABLED=true
      - PDAC_HSTS_ENABLED=false
      - PDAC_OFFLINE_MODE=false
      - PDAC_FILESYSTEM_SESSIONS_ENABLED=false
      - PDAC_SQLA_DB_HOST=mysql
      - PDAC_SQLA_DB_NAME=pda
      - PDAC_SQLA_DB_USER=root
      - PDAC_SQLA_DB_PASSWORD=qHZDZ26fPqqCfKZtWkQ9
      - PDAC_SQLA_DB_PORT=3306
      - PDAC_SAML_ENABLED=false
      - SQLALCHEMY_TRACK_MODIFICATIONS=true
      - FLASK_ENV=development
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ${PDA_LOCAL_PATH}
        target: /srv/app

  pdns:
    image: azoriansolutions/powerdns-nameserver:4.5.2-alpine-3.14-mysql
    depends_on: ['powerdns-admin']
    restart: unless-stopped
    environment:
      - AS_MYSQL_CHECK_RETRY=10
      - AS_MYSQL_CHECK_INTERVAL=4
      - PDNS_launch=gmysql
      - PDNS_gmysql_host=mysql
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=root
      - PDNS_gmysql_password=qHZDZ26fPqqCfKZtWkQ9
      - PDNS_gmysql_dbname=pda
      - PDNS_gmysql_dnssec=yes
      - PDNS_default_soa_content=pdns noc.@ 0 10800 3600 604800 3600
      - PDNS_default_ttl=3600
      - PDNS_local_address=0.0.0.0
      - PDNS_local_port=53
      - PDNS_api=yes
      - PDNS_api_key=scjfNRN4Ch2DBuhk24vr
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_any_to_tcp=yes
      - PDNS_master=no
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
      - "8081:8081/tcp"