"""add_catalog_to_domains

Revision ID: 123649227370
Revises: b24bf17725d2
Create Date: 2023-08-07 18:53:38.729196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123649227370'
down_revision = 'b24bf17725d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain',
                  sa.Column('catalog', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_domain_catalog'), 'domain', ['catalog'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain') as batch_op:
        batch_op.drop_index('ix_domain_catalog')
        batch_op.drop_column('catalog')
    # ### end Alembic commands ###
