"""Add UserPermissions Table

Revision ID: 2c892387b07d
Revises: 0d3d93f1c2e0
Create Date: 2021-06-09 15:27:13.286280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c892387b07d'
down_revision = '0d3d93f1c2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_domain', sa.Boolean(), nullable=True),
    sa.Column('remove_domain', sa.Boolean(), nullable=True),
    sa.Column('alter_record', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
