"""Add comment column in domain template record table

Revision ID: 856bb94b7040
Revises: 0fb6d23a4863
Create Date: 2019-12-09 17:17:46.257906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856bb94b7040'
down_revision = '0fb6d23a4863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_template_record',
                  sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain_template_record') as batch_op:
        batch_op.drop_column('comment')
    # ### end Alembic commands ###
