{{- if .Values.app.configSecret.generate -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SALT: {{ .Values.app.salt | b64enc }}
  SECRET_KEY: {{ .Values.app.secretKey | b64enc }}
  SQLALCHEMY_DATABASE_URI: {{ printf "mysql://%s:%s@%s/%s" .Values.database.external.username .Values.database.external.password .Values.database.external.host .Values.database.external.database | b64enc }}
  {{- if and .Values.smtp.enabled .Values.smtp.username }}
  MAIL_USERNAME: {{ .Values.smtp.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.smtp.password | b64enc }}
  {{- end }}
{{- end -}}