from .settings import Settings, Setting, SettingException

inst = Settings.instance()


class SettingReference:
    ACCOUNT_NAME_EXTRA_CHARS = 'account_name_extra_chars'
    ALLOW_USER_CREATE_DOMAIN = 'allow_user_create_domain'
    ALLOW_USER_REMOVE_DOMAIN = 'allow_user_remove_domain'
    ALLOW_USER_VIEW_HISTORY = 'allow_user_view_history'
    AUTOPROVISIONING = 'autoprovisioning'
    AUTOPROVISIONING_ATTRIBUTE = 'autoprovisioning_attribute'
    AUTO_PTR = 'auto_ptr'
    AZURE_ADMIN_GROUP = 'azure_admin_group'
    AZURE_GROUP_ACCOUNTS_DESCRIPTION = 'azure_group_accounts_description'
    AZURE_GROUP_ACCOUNTS_DESCRIPTION_RE = 'azure_group_accounts_description_re'
    AZURE_GROUP_ACCOUNTS_ENABLED = 'azure_group_accounts_enabled'
    AZURE_GROUP_ACCOUNTS_NAME = 'azure_group_accounts_name'
    AZURE_GROUP_ACCOUNTS_NAME_RE = 'azure_group_accounts_name_re'
    AZURE_OAUTH_API_URL = 'azure_oauth_api_url'
    AZURE_OAUTH_AUTHORIZE_URL = 'azure_oauth_authorize_url'
    AZURE_OAUTH_AUTO_CONFIGURE = 'azure_oauth_auto_configure'
    AZURE_OAUTH_ENABLED = 'azure_oauth_enabled'
    AZURE_OAUTH_KEY = 'azure_oauth_key'
    AZURE_OAUTH_METADATA_URL = 'azure_oauth_metadata_url'
    AZURE_OAUTH_SCOPE = 'azure_oauth_scope'
    AZURE_OAUTH_SECRET = 'azure_oauth_secret'
    AZURE_OAUTH_TOKEN_URL = 'azure_oauth_token_url'
    AZURE_OPERATOR_GROUP = 'azure_operator_group'
    AZURE_SG_ENABLED = 'azure_sg_enabled'
    AZURE_USER_GROUP = 'azure_user_group'
    BG_DOMAIN_UPDATES = 'bg_domain_updates'
    BIND_ADDRESS = 'bind_address'
    CAPTCHA_ENABLE = 'captcha_enable'
    CAPTCHA_HEIGHT = 'captcha_height'
    CAPTCHA_LENGTH = 'captcha_length'
    CAPTCHA_SESSION_KEY = 'captcha_session_key'
    CAPTCHA_WIDTH = 'captcha_width'
    CSRF_COOKIE_SECURE = 'csrf_cookie_secure'
    CUSTOM_CSS = 'custom_css'
    CUSTOM_HISTORY_HEADER = 'custom_history_header'
    DEFAULT_DOMAIN_TABLE_SIZE = 'default_domain_table_size'
    DEFAULT_RECORD_TABLE_SIZE = 'default_record_table_size'
    DELETE_SSO_ACCOUNTS = 'delete_sso_accounts'
    DENY_DOMAIN_OVERRIDE = 'deny_domain_override'
    DNSSEC_ADMINS_ONLY = 'dnssec_admins_only'
    ENABLE_API_RR_HISTORY = 'enable_api_rr_history'
    ENFORCE_API_TTL = 'enforce_api_ttl'
    FORWARD_RECORDS_ALLOW_EDIT = 'forward_records_allow_edit'
    FULLSCREEN_LAYOUT = 'fullscreen_layout'
    GITHUB_OAUTH_API_URL = 'github_oauth_api_url'
    GITHUB_OAUTH_AUTHORIZE_URL = 'github_oauth_authorize_url'
    GITHUB_OAUTH_AUTO_CONFIGURE = 'github_oauth_auto_configure'
    GITHUB_OAUTH_ENABLED = 'github_oauth_enabled'
    GITHUB_OAUTH_KEY = 'github_oauth_key'
    GITHUB_OAUTH_METADATA_URL = 'github_oauth_metadata_url'
    GITHUB_OAUTH_SCOPE = 'github_oauth_scope'
    GITHUB_OAUTH_SECRET = 'github_oauth_secret'
    GITHUB_OAUTH_TOKEN_URL = 'github_oauth_token_url'
    GOOGLE_AUTHORIZE_URL = 'google_authorize_url'
    GOOGLE_BASE_URL = 'google_base_url'
    GOOGLE_OAUTH_AUTO_CONFIGURE = 'google_oauth_auto_configure'
    GOOGLE_OAUTH_ENABLED = 'google_oauth_enabled'
    GOOGLE_OAUTH_CLIENT_ID = 'google_oauth_client_id'
    GOOGLE_OAUTH_CLIENT_SECRET = 'google_oauth_client_secret'
    GOOGLE_OAUTH_METADATA_URL = 'google_oauth_metadata_url'
    GOOGLE_OAUTH_SCOPE = 'google_oauth_scope'
    GOOGLE_TOKEN_URL = 'google_token_url'
    GRAVATAR_ENABLED = 'gravatar_enabled'
    HSTS_ENABLED = 'hsts_enabled'
    LDAP_ADMIN_GROUP = 'ldap_admin_group'
    LDAP_ADMIN_PASSWORD = 'ldap_admin_password'
    LDAP_ADMIN_USERNAME = 'ldap_admin_username'
    LDAP_BASE_DN = 'ldap_base_dn'
    LDAP_DOMAIN = 'ldap_domain'
    LDAP_ENABLED = 'ldap_enabled'
    LDAP_FILTER_BASIC = 'ldap_filter_basic'
    LDAP_FILTER_GROUP = 'ldap_filter_group'
    LDAP_FILTER_GROUPNAME = 'ldap_filter_groupname'
    LDAP_FILTER_USERNAME = 'ldap_filter_username'
    LDAP_OPERATOR_GROUP = 'ldap_operator_group'
    LDAP_SG_ENABLED = 'ldap_sg_enabled'
    LDAP_TYPE = 'ldap_type'
    LDAP_URI = 'ldap_uri'
    LDAP_USER_GROUP = 'ldap_user_group'
    LOCAL_DB_ENABLED = 'local_db_enabled'
    LOGIN_LDAP_FIRST = 'login_ldap_first'
    LOG_LEVEL = 'log_level'
    MAIL_DEBUG = 'mail_debug'
    MAIL_DEFAULT_SENDER = 'mail_default_sender'
    MAIL_PASSWORD = 'mail_password'
    MAIL_PORT = 'mail_port'
    MAIL_SERVER = 'mail_server'
    MAIL_USERNAME = 'mail_username'
    MAIL_USE_SSL = 'mail_use_ssl'
    MAIL_USE_TLS = 'mail_use_tls'
    MAINTENANCE = 'maintenance'
    MAX_HISTORY_RECORDS = 'max_history_records'
    OIDC_OAUTH_ENABLED = 'oidc_oauth_enabled'
    OIDC_OAUTH_KEY = 'oidc_oauth_key'
    OIDC_OAUTH_SECRET = 'oidc_oauth_secret'
    OIDC_OAUTH_SCOPE = 'oidc_oauth_scope'
    OIDC_OAUTH_API_URL = 'oidc_oauth_api_url'
    OIDC_OAUTH_AUTO_CONFIGURE = 'oidc_oauth_auto_configure'
    OIDC_OAUTH_METADATA_URL = 'oidc_oauth_metadata_url'
    OIDC_OAUTH_TOKEN_URL = 'oidc_oauth_token_url'
    OIDC_OAUTH_AUTHORIZE_URL = 'oidc_oauth_authorize_url'
    OIDC_OAUTH_LOGOUT_URL = 'oidc_oauth_logout_url'
    OIDC_OAUTH_USERNAME = 'oidc_oauth_username'
    OIDC_OAUTH_EMAIL = 'oidc_oauth_email'
    OIDC_OAUTH_FIRSTNAME = 'oidc_oauth_firstname'
    OIDC_OAUTH_LAST_NAME = 'oidc_oauth_last_name'
    OIDC_OAUTH_ACCOUNT_NAME_PROPERTY = 'oidc_oauth_account_name_property'
    OIDC_OAUTH_ACCOUNT_DESCRIPTION_PROPERTY = 'oidc_oauth_account_description_property'
    OPT_FIELD_ENABLED = 'opt_field_enabled'
    OTP_FORCE = 'otp_force'
    PDNS_ADMIN_LOG_LEVEL = 'pdns_admin_log_level'
    PDNS_API_KEY = 'pdns_api_key'
    PDNS_API_TIMEOUT = 'pdns_api_timeout'
    PDNS_API_URL = 'pdns_api_url'
    PDNS_VERSION = 'pdns_version'
    PORT = 'port'
    PRESERVE_HISTORY = 'preserve_history'
    PRETTY_IPV6_PTR = 'pretty_ipv6_ptr'
    PURGE = 'purge'
    PWD_ENFORCE_CHARACTERS = 'pwd_enforce_characters'
    PWD_ENFORCE_COMPLEXITY = 'pwd_enforce_complexity'
    PWD_MIN_COMPLEXITY = 'pwd_min_complexity'
    PWD_MIN_LENGTH = 'pwd_min_length'
    PWD_MIN_LOWERCASE = 'pwd_min_lowercase'
    PWD_MIN_UPPERCASE = 'pwd_min_uppercase'
    PWD_MIN_DIGITS = 'pwd_min_digits'
    PWD_MIN_SPECIAL = 'pwd_min_special'
    RECORD_HELPER = 'record_helper'
    RECORD_QUICK_EDIT = 'record_quick_edit'
    REMOTE_USER_COOKIES = 'remote_user_cookies'
    REMOTE_USER_ENABLED = 'remote_user_enabled'
    REMOTE_USER_LOGOUT_URL = 'remote_user_logout_url'
    REVERSE_RECORDS_ALLOW_EDIT = 'reverse_records_allow_edit'
    SALT = 'salt'
    SAML_ASSERTION_ENCRYPTED = 'saml_assertion_encrypted'
    SAML_ATTRIBUTE_ACCOUNT = 'saml_attribute_account'
    SAML_ATTRIBUTE_ADMIN = 'saml_attribute_admin'
    SAML_ATTRIBUTE_EMAIL = 'saml_attribute_email'
    SAML_ATTRIBUTE_GIVENNAME = 'saml_attribute_givenname'
    SAML_ATTRIBUTE_GROUP = 'saml_attribute_group'
    SAML_ATTRIBUTE_NAME = 'saml_attribute_name'
    SAML_ATTRIBUTE_SURNAME = 'saml_attribute_surname'
    SAML_ATTRIBUTE_USERNAME = 'saml_attribute_username'
    SAML_CERT = 'saml_cert'
    SAML_DEBUG = 'saml_debug'
    SAML_ENABLED = 'saml_enabled'
    SAML_GROUP_ADMIN_NAME = 'saml_group_admin_name'
    SAML_GROUP_OPERATOR_NAME = 'saml_group_operator_name'
    SAML_GROUP_TO_ACCOUNT_MAPPING = 'saml_group_to_account_mapping'
    SAML_IDP_ENTITY_ID = 'saml_idp_entity_id'
    SAML_IDP_SSO_BINDING = 'saml_idp_sso_binding'
    SAML_KEY = 'saml_key'
    SAML_LOGOUT = 'saml_logout'
    SAML_LOGOUT_URL = 'saml_logout_url'
    SAML_METADATA_CACHE_LIFETIME = 'saml_metadata_cache_lifetime'
    SAML_METADATA_URL = 'saml_metadata_url'
    SAML_NAMEID_FORMAT = 'saml_nameid_format'
    SAML_PATH = 'saml_path'
    SAML_SIGN_REQUEST = 'saml_sign_request'
    SAML_SP_CONTACT_MAIL = 'saml_sp_contact_mail'
    SAML_SP_CONTACT_NAME = 'saml_sp_contact_name'
    SAML_SP_ENTITY_ID = 'saml_sp_entity_id'
    SAML_WANT_MESSAGE_SIGNED = 'saml_want_message_signed'
    SECRET_KEY = 'secret_key'
    SERVER_EXTERNAL_SSL = 'server_external_ssl'
    SESSION_COOKIE_SECURE = 'session_cookie_secure'
    SESSION_TIMEOUT = 'session_timeout'
    SESSION_TYPE = 'session_type'
    SIGNUP_ENABLED = 'signup_enabled'
    SITE_NAME = 'site_name'
    SITE_URL = 'site_url'
    SQLALCHEMY_DATABASE_URI = 'sqlalchemy_database_uri'
    SQLALCHEMY_ENGINE_OPTIONS = 'sqlalchemy_engine_options'
    SQLALCHEMY_TRACK_MODIFICATIONS = 'sqlalchemy_track_modifications'
    TTL_OPTIONS = 'ttl_options'
    URN_VALUE = 'urn_value'
    VERIFY_SSL_CONNECTIONS = 'verify_ssl_connections'
    VERIFY_USER_EMAIL = 'verify_user_email'
    WARN_SESSION_TIMEOUT = 'warn_session_timeout'


inst.set(SettingReference.ACCOUNT_NAME_EXTRA_CHARS, Setting(**{
    'name': SettingReference.ACCOUNT_NAME_EXTRA_CHARS,
    'description': 'This determines if non-basic characters will be allowed in account names.',
    'label': 'Allow Non-Basic Characters in Account Names',
    'stype': bool,
    'default': False,
}))


inst.set(SettingReference.AUTO_PTR, Setting(**{
    'name': SettingReference.AUTO_PTR,
    'description': 'This determines if PTR records should be automatically created for A and AAAA records.',
    'label': 'Automatic PTR Setup',
    'stype': bool,
    'default': False,
}))





