FROM ubuntu:latest

RUN apt-get update && apt-get install -y pdns-backend-sqlite3 pdns-server sqlite3

COPY ./docker-common/pdns.sqlite.sql /opt/pdns.sqlite.sql
COPY ./docker-common/start-pdns.sh /data/start.sh

RUN rm -f /etc/powerdns/pdns.d/pdns.simplebind.conf
RUN rm -f /etc/powerdns/pdns.d/bind.conf

RUN chmod +x /data/start.sh && mkdir -p /var/empty/var/run

CMD /data/start.sh
