apiVersion: v1
kind: Service
metadata:
  name: powerdnsadmin
  namespace: powerdnsadmin
  labels:
    app: powerdnsadmin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: powerdnsadmin

