version: "3.3"

services:

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qHZDZ26fPqqCfKZtWkQ9
      MYSQL_DATABASE: pda
      MYSQL_USER: pda
      MYSQL_PASSWORD: qHZDZ26fPqqCfKZtWkQ9

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    depends_on: ['mysql']
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      #- PMA_ARBITRARY=1
    ports:
      - 8082:80

  pdns:
    image: azoriansolutions/powerdns-nameserver:4.5.2-alpine-3.14-mysql
    depends_on: ['mysql']
    restart: unless-stopped
    env_file: ['./env-pdns']
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
      - "8081:8081/tcp"

  powerdns-admin:
    build:
      context: ../../../
      dockerfile: ./docker/debian/Dockerfile
    image: powerdns-admin-test
    depends_on: ['pdns']
    restart: unless-stopped
    container_name: powerdns-admin-test
    env_file: ['./env-pda']
    ports:
      - "8080:80"
    volumes:
      - ../../../powerdnsadmin:/app/powerdnsadmin
